// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "maxCores"?: number;
    "maxRam"?: number;
    "cacheDir"?: string;
    "logDir"?: string;
    "workDir"?: string;
    "launcherName"?: string;
    "launcherVersion"?: string;
    "instancesDir"?: string;
    "sharedDir"?: string;
    "maxMbps"?: number;
    "minMbps"?: number;
    "cacheTTLManifest"?: string;
    "cacheTTLAssets"?: string;
    "cacheTTLVersions"?: string;
    "cacheTTLModloader"?: string;
    "cacheTTLJava"?: string;
    "cacheTTLDefault"?: string;
    "hardwareEnabled": boolean;
    "hardwareAcceleration": boolean;
    "gpuType": string;
    "gpuPreset": string;
    "javaMode": string;
    "javaCustomPath": string;
    "proxyEnabled": boolean;
    "proxyHost": string;
    "proxyPort": number;
    "proxyUser": string;
    "proxyPass": string;
    "authVerify": boolean;
    "windowWidth": number;
    "windowHeight": number;
    "fullscreen": boolean;
    "javaArgs": string;
    "gameArgs": string;
    "offlineMode": boolean;
    "compatMode": boolean;
    "detailedLogs": boolean;
    "concurrentDownloads": number;
    "verifyIntegrity": boolean;
    "verifyBeforeLaunch": boolean;

    /**
     * SeparateGameDir indica si el gameDir es <workDir>/game (true) o el
     * propio workDir (false). nil equivale a true. En modo Minecraft se
     * fuerza a false para usar .minecraft directamente como gameDir.
     */
    "separateGameDir"?: boolean | null;
}

/**
 * DirMode define los modos de directorio de trabajo del launcher.
 */
export enum DirMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeNormal = "normal",
    ModeMinecraft = "minecraft",
    ModePortable = "portable",
    ModeCustom = "custom",
};
