// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accounts$0 from "../../Core/Accounts/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cache$0 from "../../Core/Cache/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloader$0 from "../../Core/Downloader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "../../Core/Launcher/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../../Core/Launcher/History/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as instance$0 from "../../Core/Launcher/Instance/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "../../Core/Launcher/Profile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modloader$0 from "../../Core/ModLoader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engineconfig$0 from "./engineconfig/models.js";

export type AccountCredentials = accounts$0.AccountCredentials;

export type AccountInfo = accounts$0.AccountInfo;

export type AddVersionReq = instance$0.AddVersionReq;

export type AuthlibLoginReq = accounts$0.AuthlibLoginReq;

export type CacheInfo = cache$0.Info;

export type CrashEntry = history$0.CrashEntry;

export type CreateAccountReq = accounts$0.CreateAccountReq;

export type CreateInstanceReq = instance$0.CreateInstanceReq;

/**
 * DirectoryInfo describe el estado actual del directorio de trabajo para la UI.
 */
export interface DirectoryInfo {
    "mode": engineconfig$0.DirMode;
    "customPath": string;
    "configured": boolean;
    "workDir": string;
    "normalDir": string;
    "minecraftDir": string;
    "minecraftExists": boolean;
    "portableDir": string;
}

export type DownloadFilter = downloader$0.DownloadFilter;

export interface DownloadInfo {
    "id": string;
    "version": string;
    "state": DownloadState;
    "error"?: string;
}

export type DownloadProgress = downloader$0.DownloadProgress;

export type DownloadState = downloader$0.DownloadState;

export interface EngineInfo {
    "name": string;
    "version": string;
    "author": string;
    "goVersion": string;
    "os": string;
    "arch": string;
    "numCpu": number;
    "numGoroutine": number;
    "launcherName"?: string;
    "launcherVersion"?: string;
}

export type ExecutionPlan = modloader$0.ExecutionPlan;

export interface GameResp {
    "id": string;
    "pid": number;
    "version": string;
    "status": GameStatus;
    "startTime"?: string;
    "exitCode": number;
    "logPath"?: string;
    "crashLog"?: string;
    "crashReason"?: string;
    "crashCategory"?: string;
}

export type GameStatus = launcher$0.GameStatus;

export type HistoryEntry = history$0.Entry;

export type InstalledLoader = modloader$0.InstalledLoader;

export interface InstalledVersion {
    "id": string;
    "type": string;
}

export type InstanceInfo = instance$0.InstanceInfo;

export type InstanceLaunchConfig = instance$0.InstanceLaunchConfig;

export type InstanceLaunchResult = instance$0.InstanceLaunchResult;

export type InstanceMetadata = instance$0.InstanceMetadata;

export type InstanceStats = history$0.InstanceStats;

export type InstanceVerifyProgress = instance$0.InstanceVerifyProgress;

export interface IntegrityProgress {
    "state": IntegrityState;
    "phase": string;
    "scope": string;
    "currentVersion": string;
    "currentFile": string;
    "tasksTotal": number;
    "tasksDone": number;
    "filesMissing": number;
    "filesRestored": number;
    "filesCorrupt": number;
    "filesSkipped": number;
    "versionsScanned": number;
    "percent": number;
    "startedAt"?: string;
    "finishedAt"?: string;
    "skipped"?: IntegritySkipped[] | null;
}

export interface IntegritySkipped {
    "file": string;
    "reason": string;
}

export enum IntegrityState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    IntegrityStateIdle = "idle",
    IntegrityStateRunning = "running",
    IntegrityStateCompleted = "completed",
    IntegrityStateCancelled = "cancelled",
    IntegrityStateError = "error",
};

export type LaunchConfig = launcher$0.LaunchConfig;

export interface ModLoaderInstallResult {
    "sessionId": string;
    "status": string;
}

export type ModLoaderVersion = modloader$0.LoaderVersion;

export type Profile = profile$0.Profile;

export type UpdateMetadataReq = instance$0.UpdateMetadataReq;

export type VerifyResult = instance$0.VerifyResult;

export interface VersionInfo {
    "id": string;
    "type": string;
    "url": string;
    "time": string;
}

export interface VersionStats {
    "version": string;
    "playCount": number;
    "lastPlayed": number;
    "totalPlayed": number;
}
