// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Queue representa la cola temporal de reproducción.
 */
export interface Queue {
    "tracks": string[] | null;
    "currentIndex": number;
    "currentPath": string;
}
