// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "../Music/models.js";

export interface CoverCacheInfo {
    "total": number;
    "valid": number;
    "expired": number;
    "size": number;
}

export interface MusicMetadataEntry {
    "title": string;
    "artist": string;
    "album"?: string;
    "year"?: number;
    "duration": number;
    "trackNumber"?: number;
    "genre"?: string;
    "hasCover": boolean;
    "coverMime"?: string;
    "cachedAt": string;
    "fileModTime"?: string;
    "fileSize"?: number;
}

export type MusicScanProgress = music$0.ScanProgress;

export interface ScreenshotInfo {
    "name": string;
    "path": string;
    "size": number;
    "time"?: string;
}
