// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Playlist representa una colección local de música.
 * Puede tener rutas absolutas o relativas (relativas a RootDir o a MusicFolder).
 */
export interface Playlist {
    "id": string;
    "title": string;
    "favorite": boolean;
    "pinned": boolean;
    "trackPaths": string[] | null;
    "customColor"?: string;

    /**
     * ruta a imagen custom (relativa o absoluta)
     */
    "customCover"?: string;
    "createdAt": string;
    "updatedAt": string;

    /**
     * cacheado en Go, no recalcular en frontend
     */
    "totalDuration"?: number;
    "trackCount"?: number;

    /**
     * carátulas thumb (data URI) de las primeras 4 pistas, cacheadas para lectura instantánea
     */
    "previewCovers"?: string[] | null;
}
