// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MusicService gestiona biblioteca musical, scanner y playlists.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Config$0 from "../../Config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Handlers$0 from "../../Handlers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as music$0 from "../../Music/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as musichistory$0 from "../../Music/MusicHistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nowplaying$0 from "../../Music/NowPlaying/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playlists$0 from "../../Music/Playlist/models.js";

export function AddMusicFolder(folder: string): $CancellablePromise<void> {
    return $Call.ByID(612210662, folder);
}

export function AddMusicHistory(path: string, title: string, artist: string, coverUrl: string): $CancellablePromise<musichistory$0.Entry[] | null> {
    return $Call.ByID(1476128830, path, title, artist, coverUrl);
}

export function CancelMusicScan(): $CancellablePromise<boolean> {
    return $Call.ByID(4255298988);
}

export function ClearCoverCache(): $CancellablePromise<number> {
    return $Call.ByID(2269915610);
}

export function ClearMusicCache(): $CancellablePromise<number> {
    return $Call.ByID(1065421166);
}

export function ClearMusicHistory(): $CancellablePromise<void> {
    return $Call.ByID(3340206836);
}

export function ClearNowPlayingQueue(): $CancellablePromise<void> {
    return $Call.ByID(102365450);
}

export function CreatePlaylist(title: string, trackPaths: string[] | null): $CancellablePromise<playlists$0.Playlist | null> {
    return $Call.ByID(1029522962, title, trackPaths);
}

export function DeletePlaylist(id: string): $CancellablePromise<void> {
    return $Call.ByID(1080381029, id);
}

export function GetAllMusicMetadata(): $CancellablePromise<{ [_ in string]?: Handlers$0.MusicMetadataEntry } | null> {
    return $Call.ByID(1312911959);
}

export function GetCachedCover(trackPath: string): $CancellablePromise<string> {
    return $Call.ByID(1209204845, trackPath);
}

export function GetCoverCacheInfo(): $CancellablePromise<Handlers$0.CoverCacheInfo> {
    return $Call.ByID(4210051799);
}

export function GetCoverCacheStatus(): $CancellablePromise<Handlers$0.CoverCacheInfo> {
    return $Call.ByID(1794837685);
}

export function GetMusicCoverBase64(trackPath: string, variant: string): $CancellablePromise<string> {
    return $Call.ByID(1410117577, trackPath, variant);
}

export function GetMusicFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1662006088);
}

export function GetMusicHistory(): $CancellablePromise<musichistory$0.Entry[] | null> {
    return $Call.ByID(1468782817);
}

export function GetMusicLibraryStats(): $CancellablePromise<music$0.MusicLibraryStats> {
    return $Call.ByID(410220721);
}

export function GetMusicMetadata(trackPath: string): $CancellablePromise<Handlers$0.MusicMetadataEntry> {
    return $Call.ByID(3876157826, trackPath);
}

export function GetMusicPanelConfig(): $CancellablePromise<Config$0.MusicPanelConfig> {
    return $Call.ByID(4237248453);
}

export function GetMusicScanProgress(): $CancellablePromise<Handlers$0.MusicScanProgress> {
    return $Call.ByID(1178649897);
}

export function GetMusicTracksBatch(paths: string[] | null, coverVariant: string): $CancellablePromise<music$0.MusicTrackDTO[] | null> {
    return $Call.ByID(151871929, paths, coverVariant);
}

export function GetMusicTracksPaged(offset: number, limit: number, coverVariant: string, query: string): $CancellablePromise<music$0.MusicPageDTO> {
    return $Call.ByID(2710123096, offset, limit, coverVariant, query);
}

export function GetNowPlayingQueue(): $CancellablePromise<nowplaying$0.Queue> {
    return $Call.ByID(905154589);
}

export function GetPlaylist(id: string): $CancellablePromise<playlists$0.Playlist | null> {
    return $Call.ByID(1102271002, id);
}

export function ImportPlaylistFile(path: string): $CancellablePromise<playlists$0.Playlist | null> {
    return $Call.ByID(1905925989, path);
}

export function InitializeMusicLibrary(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1384286656);
}

export function ListPlaylists(): $CancellablePromise<playlists$0.Playlist[] | null> {
    return $Call.ByID(2680807671);
}

export function PickCustomCoverFile(): $CancellablePromise<string> {
    return $Call.ByID(3308263775);
}

export function PickMusicFolder(): $CancellablePromise<string> {
    return $Call.ByID(3939493244);
}

export function PickPlaylistFile(): $CancellablePromise<string> {
    return $Call.ByID(3054180769);
}

export function RebuildMusicIndex(): $CancellablePromise<void> {
    return $Call.ByID(1218183638);
}

export function RefreshCachedCover(trackPath: string): $CancellablePromise<void> {
    return $Call.ByID(2232360132, trackPath);
}

export function RemoveMusicFolder(folder: string): $CancellablePromise<void> {
    return $Call.ByID(2147387175, folder);
}

export function SaveCachedCover(trackPath: string, b64Data: string, mime: string): $CancellablePromise<void> {
    return $Call.ByID(4275770634, trackPath, b64Data, mime);
}

export function SaveMusicMetadata(trackPath: string, title: string, artist: string, duration: number, coverData: string, mime: string): $CancellablePromise<void> {
    return $Call.ByID(3600916625, trackPath, title, artist, duration, coverData, mime);
}

export function ScanAllMusicFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(539133428);
}

export function ScanMusicFolder(folder: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3972271756, folder);
}

export function SetMusicFolder(folder: string): $CancellablePromise<void> {
    return $Call.ByID(3034159247, folder);
}

export function SetMusicFolders(folders: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2928399540, folders);
}

export function SetNowPlayingQueue(tracks: string[] | null, idx: number, curPath: string): $CancellablePromise<void> {
    return $Call.ByID(1605188521, tracks, idx, curPath);
}

export function UpdateMusicPanelConfig(p: Config$0.MusicPanelConfig): $CancellablePromise<void> {
    return $Call.ByID(3908981832, p);
}

export function UpdatePlaylist(id: string, p: playlists$0.Playlist): $CancellablePromise<playlists$0.Playlist | null> {
    return $Call.ByID(3372495799, id, p);
}
