// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountService gestiona cuentas, perfiles y Rich Presence.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Config$0 from "../../Config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export function CancelAuthlibLogin(): $CancellablePromise<void> {
    return $Call.ByID(586676624);
}

export function CreateAccount(req: engine$0.CreateAccountReq): $CancellablePromise<engine$0.AccountInfo | null> {
    return $Call.ByID(3334042519, req);
}

export function CreateProfile(p: engine$0.Profile | null): $CancellablePromise<void> {
    return $Call.ByID(3464276877, p);
}

export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(469259954, id);
}

export function DeleteProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(2877401000, name);
}

export function GetAccount(id: string): $CancellablePromise<engine$0.AccountInfo | null> {
    return $Call.ByID(2560480119, id);
}

export function GetAccountAssets(id: string): $CancellablePromise<void> {
    return $Call.ByID(1972310486, id);
}

export function GetAccountsAutoRefresh(): $CancellablePromise<boolean> {
    return $Call.ByID(3190007454);
}

export function GetProfile(name: string): $CancellablePromise<engine$0.Profile | null> {
    return $Call.ByID(4133132141, name);
}

export function GetRichPresenceConfig(): $CancellablePromise<Config$0.RichPresenceConfig> {
    return $Call.ByID(857131409);
}

export function GetSelectedAccount(): $CancellablePromise<string> {
    return $Call.ByID(1012731648);
}

export function GetSelectedProfile(): $CancellablePromise<string> {
    return $Call.ByID(246897362);
}

export function GetSelectedVersion(): $CancellablePromise<string> {
    return $Call.ByID(3254976683);
}

export function ListAccounts(): $CancellablePromise<engine$0.AccountInfo[] | null> {
    return $Call.ByID(29854056);
}

export function ListProfiles(): $CancellablePromise<{ [_ in string]?: engine$0.Profile | null } | null> {
    return $Call.ByID(3517630246);
}

export function LoginAuthlib(req: engine$0.AuthlibLoginReq): $CancellablePromise<void> {
    return $Call.ByID(3946931730, req);
}

export function RefreshAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(4143805026, id);
}

export function RefreshAllAccounts(): $CancellablePromise<number> {
    return $Call.ByID(1503204442);
}

export function ResolveAccountCredentials(id: string): $CancellablePromise<engine$0.AccountCredentials | null> {
    return $Call.ByID(3253219975, id);
}

export function SetAccountsAutoRefresh(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1268951506, v);
}

export function SetRichPresenceEnabled(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1336721844, v);
}

export function SetSelectedAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(1222245220, id);
}

export function SetSelectedProfile(name: string): $CancellablePromise<void> {
    return $Call.ByID(946293158, name);
}

export function SetSelectedVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(2348833711, version);
}

export function UpdateAccount(id: string, req: engine$0.CreateAccountReq): $CancellablePromise<engine$0.AccountInfo | null> {
    return $Call.ByID(3709818308, id, req);
}

export function UpdateProfile(name: string, p: engine$0.Profile | null): $CancellablePromise<void> {
    return $Call.ByID(156755974, name, p);
}
