// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppearanceService gestiona personalizacion visual y assets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Config$0 from "../../Config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as assets$0 from "../../Core/Assets/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMusic(name: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(3919060778, name, src);
}

export function DeleteFontFile(name: string): $CancellablePromise<void> {
    return $Call.ByID(1927129320, name);
}

export function DownloadGalleryImageAsBackground(url: string, author: string, modName: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(1485718247, url, author, modName, title);
}

export function GetLauncherAssets(): $CancellablePromise<assets$0.Assets> {
    return $Call.ByID(3626947025);
}

export function GetUIScale(): $CancellablePromise<number> {
    return $Call.ByID(1519345456);
}

export function ImportBackground(src: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(3545550785, src, kind);
}

export function ImportFont(src: string): $CancellablePromise<string> {
    return $Call.ByID(3170947820, src);
}

export function ListFontFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1457993468);
}

export function ListMusic(): $CancellablePromise<assets$0.MusicSlot[] | null> {
    return $Call.ByID(1707351855);
}

export function ListScreenshots(): $CancellablePromise<$models.ScreenshotInfo[] | null> {
    return $Call.ByID(3794420841);
}

export function PickBackgroundFile(kind: string): $CancellablePromise<string> {
    return $Call.ByID(4082079579, kind);
}

export function PickFontFile(): $CancellablePromise<string> {
    return $Call.ByID(2828324294);
}

export function PickMusicFile(): $CancellablePromise<string> {
    return $Call.ByID(4222068354);
}

export function ReadMusicFile(src: string): $CancellablePromise<string | null> {
    return $Call.ByID(1272649981, src);
}

export function RemoveMusic(name: string): $CancellablePromise<void> {
    return $Call.ByID(1634281703, name);
}

export function SaveLauncherAssets(asset: assets$0.Assets): $CancellablePromise<void> {
    return $Call.ByID(657134504, asset);
}

export function SetHideLauncher(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(2271150724, v);
}

export function SetIdle(idle: Config$0.IdleConfig): $CancellablePromise<void> {
    return $Call.ByID(3587740046, idle);
}

export function SetScreenshotAsBackground(relPath: string): $CancellablePromise<string> {
    return $Call.ByID(899305012, relPath);
}

export function SetUIScale(percent: number): $CancellablePromise<void> {
    return $Call.ByID(3298425212, percent);
}

export function UpdatePersonalization(p: Config$0.Personalization): $CancellablePromise<void> {
    return $Call.ByID(159447755, p);
}
