// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BackgroundConfig {
    "type": string;
    "imagePath": string;
    "videoPath": string;
    "dynamicImages": string[] | null;
    "dynamicOrder": string;
    "dynamicInterval": number;
    "imageAuthor"?: string;
    "imageModName"?: string;
    "imageUrl"?: string;
}

export interface Config {
    "minecraftConfig": MinecraftConfig;
    "launcher": LauncherConfig;
    "personalization": Personalization;
    "idle": IdleConfig;
    "richPresence": RichPresenceConfig;
    "musicPanel": MusicPanelConfig;
    "extraData": ExtraData;
    "firstLaunch": boolean;
}

export interface ExtraData {
    "assets": string;
    "accounts": string;
    "history": string;
    "profiles": string;
    "crashHistory": string;
    "playlists": string;
    "musicHistory": string;
}

export interface IdleConfig {
    "autoCloseModals": boolean;
    "idleMinutes": number;
    "configCheckEnabled": boolean;
    "configCheckMinutes": number;
}

export interface LauncherConfig {
    "maxRamGB": number;
    "maxMbps": number;
    "concurrentDownloads": number;
    "hideLauncherOnLaunch": boolean;
    "verifyIntegrity": boolean | null;
    "integritySector": string;
    "checkForUpdatesOnStart": boolean;
    "launchAfterInstall": boolean;
    "verifyBeforeLaunch": boolean | null;
}

export interface MinecraftConfig {
    "hardwareEnabled": boolean;
    "hardwareAcceleration": boolean;
    "gpuType": string;
    "gpuPreset": string;
    "javaMode": string;
    "javaCustomPath": string;
    "proxyEnabled": boolean;
    "proxyHost": string;
    "proxyPort": number;
    "proxyUser": string;
    "proxyPass": string;
    "authVerify": boolean;
    "windowWidth": number;
    "windowHeight": number;
    "fullscreen": boolean;
    "javaArgs": string;
    "gameArgs": string;
    "offlineMode": boolean;
    "compatMode": boolean;
    "detailedLogs": boolean;

    /**
     * SeparateGameDir: true = <workDir>/game, false = workDir como gameDir
     * (nil equivale a true). En modo Minecraft se fuerza a false.
     */
    "separateGameDir"?: boolean | null;
}

export interface MusicConfig {
    "enabled": boolean;
    "position": string;
    "coverStyle": string;
    "discRotation": boolean;
    "volume": number;
}

export interface MusicPanelConfig {
    "musicFolder": string;
    "musicFolders"?: string[] | null;

    /**
     * square | disc | huge
     */
    "coverStyle": string;

    /**
     * vibrant | dominant | muted | least | random
     */
    "colorMode": string;
    "pageSize": number;
    "showCovers": boolean | null;
    "allowAbsolute": boolean | null;

    /**
     * carátula enorme predomina
     */
    "nowPlayingHuge"?: boolean | null;

    /**
     * square | disc | huge (específico Ahora suena)
     */
    "nowPlayingCover"?: string;

    /**
     * tamaño carátula predominante 15..30 rem
     */
    "nowPlayingHugeSize"?: number | null;

    /**
     * off | hourly | daily | onLaunch
     */
    "autoScan"?: string;

    /**
     * background | library | auto
     */
    "smtcSource"?: string;

    /**
     * 0 transparente .. 1 opaco (fondo del panel Música ::after)
     */
    "coverOpacity"?: number | null;
}

export interface Personalization {
    "uiScale": number;
    "background": BackgroundConfig;
    "backgroundMusic": MusicConfig;
    "fontPrimary": string;
    "fontSecondary": string;
    "fontPrimaryColor": string;
    "fontSecondaryColor": string;
    "fontPrimarySize": number;
    "fontSecondarySize": number;
    "colors": ThemeColors;
    "recentColors": string[] | null;
    "animations": boolean;
    "blur": boolean;
    "shadows": boolean;
    "textShadow": boolean;
    "textShadowIntensity": number;
}

export interface RichPresenceConfig {
    "enabled": boolean | null;
}

export interface ThemeColors {
    "sidebar": string;
    "modal": string;
    "buttons": string;
    "borderModal": string;
    "border": string;
    "progress": string;
    "playButton": string;
    "buttonPrimary": string;
    "error": string;
    "success": string;
    "tag": string;
    "warning": string;
}
