// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AdvancedConfig {
    "authlib"?: AuthLibConfig;
    "javaExec"?: string;
    "useOfficialJava": boolean;
    "minRam": number;
    "maxRam": number;
    "gcPreset"?: string;
    "gpuPreference"?: string;
    "hardwareAcceleration"?: boolean | null;
    "fullscreen": boolean;
    "customResolution": boolean;
    "resWidth": number;
    "resHeight": number;
    "windowTitle"?: string;
    "demoUser": boolean;
    "userType"?: string;
    "logLevel"?: string;
    "detailedLogs": boolean;
    "runtimeDir"?: string;
    "gameDir"?: string;
    "assetsDir"?: string;
    "librariesDir"?: string;
    "versionsDir"?: string;
    "nativesBaseDir"?: string;
    "nativesDir"?: string;
    "cacheDir"?: string;
    "workingDir"?: string;
    "assetIndexId"?: string;
    "assetIndexType"?: string;
    "assetIndexUrl"?: string;
    "assetIndexVirtual"?: boolean | null;
    "disableAssets": boolean;
    "forceReindex": boolean;
    "serverAddress"?: string;
    "serverPort": number;
    "quickPlayPath"?: string;
    "minecraftLogConfig"?: string;
    "maxMetaspaceSize"?: number;
    "stackSize"?: number;
    "javaArgs"?: string[] | null;
    "gameArgs"?: string[] | null;
    "disableLibraries": boolean;
    "skipLibraryCheck": boolean;
    "skipAssetCheck": boolean;
    "skipNativeExtract": boolean;
    "skipVersionDownload": boolean;
    "profileVersion"?: string;
    "baseVersion"?: string;
    "environmentVars"?: { [_ in string]?: string } | null;
    "jvmFlags"?: { [_ in string]?: boolean } | null;
    "downloadConcurrency"?: number;
    "maxRetries"?: number;
    "connectionTimeout"?: number;
    "proxyHost"?: string;
    "proxyPort"?: number;
    "proxyUser"?: string;
    "proxyPass"?: string;
    "libraryCustomRepo"?: string;
    "assetCustomUrl"?: string;
    "forceRedownload": boolean;
    "javaModulePath"?: string;
    "javaAddModules"?: string[] | null;
    "javaAddExports"?: string[] | null;
    "javaAddOpens"?: string[] | null;
    "directMemorySize"?: number;
    "reservedCodeCache"?: number;
    "metaspaceSize"?: number;
    "verifyBeforeLaunch": boolean;
    "allowServerList"?: boolean | null;
    "allowMultiplayer"?: boolean | null;
    "allowChat"?: boolean | null;
    "allowRealms"?: boolean | null;
    "framerateLimit"?: number;
    "renderer"?: string;
    "preLaunchCommand"?: string;
    "postLaunchCommand"?: string;
    "logKeepDays"?: number;
    "logMaxFiles"?: number;
    "gameLogLines"?: number;
    "libraryExcludePatterns"?: string[] | null;
}

export interface AuthLibConfig {
    "enabled": boolean;
    "injectorPath"?: string;
    "authServerUrl"?: string;
    "preVerifyServer": boolean;
    "preVerifyTimeout"?: number;
    "skipServerCheck": boolean;
    "username"?: string;
    "serverToken"?: string;
}

export enum GameStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GameStarting = "starting",
    GameRunning = "running",
    GameExited = "exited",
    GameCrashed = "crashed",
    GameStopped = "stopped",
};

export interface LaunchConfig {
    "Version": string;
    "Username": string;
    "InstanceID": string;
    "InstanceName": string;
    "UUID": string;
    "AccessToken": string;
    "XUID": string;
    "ClientID": string;
    "LauncherName": string;
    "LauncherVersion": string;
    "LogDir": string;
    "Advanced": AdvancedConfig | null;
    "Profile": string;
}
