// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MusicLibraryStats para debugging y Settings.
 */
export interface MusicLibraryStats {
    "totalTracks": number;
    "totalFolders": number;
    "cachedTracks": number;
    "cachedCovers": number;
    "missingMetadata": number;
    "missingCovers": number;
    "lastScanUnix": number;
    "databaseSizeBytes": number;
}

export interface MusicPageDTO {
    "tracks": MusicTrackDTO[] | null;
    "total": number;
    "offset": number;
    "limit": number;
}

/**
 * MusicTrackDTO para paginación con carátulas en base64
 */
export interface MusicTrackDTO {
    "path": string;
    "fileName": string;
    "title": string;
    "artist": string;
    "album": string;
    "year": number;
    "duration": number;
    "genre": string;
    "hasCover": boolean;
    "coverMime"?: string;

    /**
     * data:image/...;base64, 128x128 comprimida
     */
    "coverThumb"?: string;

    /**
     * data:image/...;base64, original
     */
    "coverRaw"?: string;
}

/**
 * ScanProgress progreso exacto sin redondeo - extendido para incremental
 */
export interface ScanProgress {
    "scanning": boolean;
    "current": number;
    "total": number;
    "folder": string;
    "currentFile": string;
    "discovered": number;
    "processed": number;
    "skipped": number;
    "added": number;
    "updated": number;
    "removed": number;
    "errors": number;
}
