// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launcher$0 from "../models.js";

export interface AddVersionReq {
    "version": string;
    "client": boolean | null;
    "libraries": boolean | null;
    "natives": boolean | null;
    "assets": boolean | null;
    "java": boolean | null;
    "maxRetries": number | null;
    "concurrency": number | null;
    "skipVerify": boolean | null;
}

export interface CreateInstanceReq {
    "name": string;
    "version"?: string;
    "title"?: string;
    "description"?: string;
    "icon"?: string;
    "banner"?: string;
    "group"?: string;
    "tags"?: string[] | null;
    "favorite"?: boolean | null;
    "pinned"?: boolean | null;
    "launchConfig"?: InstanceLaunchConfig | null;
}

export interface InstanceInfo {
    "name": string;
    "title": string;
    "versions": string[] | null;
    "favorite": boolean;
    "pinned": boolean;
    "group": string;
    "tags": string[] | null;
    "lastPlayed": string;
    "playTime": number;
}

export interface InstanceLaunchConfig {
    "version"?: string;
    "javaExec"?: string;
    "minRam"?: number | null;
    "maxRam"?: number | null;
    "useOfficialJava"?: boolean | null;
    "fullscreen"?: boolean | null;
    "hardwareAcceleration"?: boolean | null;
    "gcPreset"?: string | null;
    "gpuPreference"?: string | null;
    "customResolution"?: boolean | null;
    "resWidth"?: number | null;
    "resHeight"?: number | null;
    "demoUser"?: boolean | null;
    "windowTitle"?: string;
    "userType"?: string;
    "advanced"?: launcher$0.AdvancedConfig | null;
    "gameDir"?: string;
    "assetsDir"?: string;
    "librariesDir"?: string;
    "nativesDir"?: string;
    "versionsDir"?: string;
    "runtimeDir"?: string;
    "cacheDir"?: string;
    "assetIndexId"?: string;
    "disableAssets"?: boolean | null;
    "serverAddress"?: string;
    "serverPort"?: number | null;
    "maxMetaspaceSize"?: number | null;
    "stackSize"?: number | null;
    "allowServerList"?: boolean | null;
    "allowMultiplayer"?: boolean | null;
    "allowChat"?: boolean | null;
    "allowRealms"?: boolean | null;
    "framerateLimit"?: number | null;
    "logKeepDays"?: number | null;
    "logMaxFiles"?: number | null;
    "preLaunchCommand"?: string;
    "postLaunchCommand"?: string;
    "environmentVars"?: { [_ in string]?: string } | null;
    "javaArgs"?: string[] | null;
    "gameArgs"?: string[] | null;

    /**
     * Logs detallados: añade --log-level debug a los argumentos del juego.
     */
    "detailedLogs"?: boolean | null;

    /**
     * Backups automáticos: "off" | "session" (al cerrar una sesión de juego) |
     * "hours" | "days" (cada BackupInterval horas/días tras la última copia).
     * LastBackupAt lo gestiona el backend y solo indica cuándo se hizo la
     * última copia (formato RFC3339).
     */
    "backupSchedule"?: string;
    "backupInterval"?: number;
    "lastBackupAt"?: string;
    "skipLibraryCheck"?: boolean | null;
    "skipAssetCheck"?: boolean | null;
    "skipNativeExtract"?: boolean | null;
    "skipVersionDownload"?: boolean | null;
}

export interface InstanceLaunchResult {
    "id": string;
    "pid": number;
    "version": string;
    "status": string;
    "logPath": string;
}

export interface InstanceMetadata {
    "id": string;
    "name": string;
    "title": string;
    "description": string;
    "icon": string;
    "banner": string;
    "group": string;
    "tags": string[] | null;
    "favorite": boolean;
    "pinned": boolean;
    "createdAt": string;
    "lastPlayed": string;
    "playTime": number;
    "versions": string[] | null;
    "configPath": string;
}

/**
 * InstanceVerifyProgress es el estado consultable (por polling) de la
 * verificación de integridad asíncrona de una instancia concreta.
 */
export interface InstanceVerifyProgress {
    /**
     * "idle" | "verifying" | "done" | "error" | "cancelled"
     */
    "state": string;
    "phase": string;
    "version": string;
    "percent": number;

    /**
     * versiones verificadas
     */
    "found": number;

    /**
     * problemas encontrados
     */
    "issues": number;
    "error": string;
}

export interface UpdateMetadataReq {
    "title"?: string;
    "description"?: string;
    "icon"?: string;
    "banner"?: string;
    "group"?: string;
    "tags"?: string[] | null;
    "favorite"?: boolean | null;
    "pinned"?: boolean | null;
}

export interface VerifyIssue {
    "type": string;
    "file": string;
    "message": string;
}

export interface VerifyResult {
    "valid": boolean;
    "version": string;
    "issues": VerifyIssue[] | null;
}
