// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModsService instala contenido de Modrinth (mods, shaders, texturas y
 * modpacks .mrpack) en el juego global o en instancias.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "../../Core/Mods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export function CancelModContent(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1759348645, sessionID);
}

export function ContentSubdirFor(projectType: string): $CancellablePromise<string> {
    return $Call.ByID(1089260601, projectType);
}

export function DeleteInstalledContent(destination: string, instance: string, kind: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2288698818, destination, instance, kind, name);
}

/**
 * GetContentIcon devuelve la ruta relativa del icono de un contenido
 * instalado (vacío si no tiene). La UI la resuelve con loadLocal.
 */
export function GetContentIcon(destination: string, instance: string, kind: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3160662762, destination, instance, kind, name);
}

export function GlobalGameDir(): $CancellablePromise<string> {
    return $Call.ByID(3957045962);
}

export function InstallModContent(req: engine$0.ModContentRequest): $CancellablePromise<engine$0.ModContentResult | null> {
    return $Call.ByID(176018508, req);
}

export function InstallModpack(req: engine$0.ModpackInstallRequest): $CancellablePromise<engine$0.ModContentResult | null> {
    return $Call.ByID(3237784662, req);
}

export function InstanceGameDir(name: string): $CancellablePromise<string> {
    return $Call.ByID(4154256042, name);
}

export function ListInstalledContent(destination: string, instance: string): $CancellablePromise<mods$0.InstalledFile[] | null> {
    return $Call.ByID(1028243101, destination, instance);
}

/**
 * MoveInstalledContent traslada un archivo instalado entre destinos.
 */
export function MoveInstalledContent(srcDestination: string, srcInstance: string, kind: string, name: string, dstDestination: string, dstInstance: string): $CancellablePromise<void> {
    return $Call.ByID(814340820, srcDestination, srcInstance, kind, name, dstDestination, dstInstance);
}

/**
 * RevealInstalledContent abre el explorador con el archivo instalado.
 */
export function RevealInstalledContent(destination: string, instance: string, kind: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1213399884, destination, instance, kind, name);
}

export function SetInstalledContentEnabled(destination: string, instance: string, kind: string, name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2750183314, destination, instance, kind, name, enabled);
}
