// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CrashEntry {
    "id": string;
    "timestamp": number;
    "version": string;
    "exit_code": number;
    "crash_reason"?: string;
    "crash_category"?: string;
    "launcherLogPath"?: string;
    "minecraftLogPath"?: string;
    "jvmLogPath"?: string;
}

export interface Entry {
    "id": string;
    "timestamp": number;
    "instance_id"?: string;
    "instance_name"?: string;
    "version": string;
    "player_name": string;
    "play_time_seconds": number;
    "exit_code": number;
    "crash_reason"?: string;
    "max_ram"?: number;
}

export interface InstanceStats {
    "totalPlayTime": number;
    "totalSessions": number;
    "firstPlayed": number;
    "lastPlayed": number;
    "weeklyPlayTime": number;
    "weeklySessions": number;
    "weeklyVersions": string[] | null;
    "versions": VersionStat[] | null;
    "running": boolean;
}

export interface VersionStat {
    "version": string;
    "playCount": number;
    "totalPlayed": number;
    "firstPlayed": number;
    "lastPlayed": number;
}
