// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameService gestiona ejecucion de juegos e historial.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearHistory(): $CancellablePromise<number> {
    return $Call.ByID(386887259);
}

export function DeleteHistoryEntry(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1819350863, id);
}

export function GetCrashHistory(): $CancellablePromise<engine$0.CrashEntry[] | null> {
    return $Call.ByID(1489337485);
}

export function GetGame(id: string): $CancellablePromise<engine$0.GameResp | null> {
    return $Call.ByID(2036468818, id);
}

export function GetGameLaunchInfo(id: string): $CancellablePromise<string> {
    return $Call.ByID(2811398661, id);
}

export function GetHistory(): $CancellablePromise<engine$0.HistoryEntry[] | null> {
    return $Call.ByID(2551345608);
}

export function GetHistoryByVersion(version: string): $CancellablePromise<engine$0.HistoryEntry[] | null> {
    return $Call.ByID(1200158519, version);
}

export function GetHistoryStats(): $CancellablePromise<$models.HistoryStatsResult> {
    return $Call.ByID(3934949195);
}

export function GetInstanceStats(name: string): $CancellablePromise<engine$0.InstanceStats> {
    return $Call.ByID(323567222, name);
}

export function GetMostPlayed(limit: number): $CancellablePromise<engine$0.HistoryEntry[] | null> {
    return $Call.ByID(2460601428, limit);
}

export function GetRecentHistory(limit: number): $CancellablePromise<engine$0.HistoryEntry[] | null> {
    return $Call.ByID(1867982661, limit);
}

export function LaunchInstance(name: string, username: string, uuid: string, accessToken: string, xuid: string, clientID: string): $CancellablePromise<engine$0.InstanceLaunchResult | null> {
    return $Call.ByID(1574738588, name, username, uuid, accessToken, xuid, clientID);
}

export function LaunchMinecraft(cfg: engine$0.LaunchConfig): $CancellablePromise<engine$0.GameResp | null> {
    return $Call.ByID(2624492734, cfg);
}

export function ListGames(): $CancellablePromise<engine$0.GameResp[] | null> {
    return $Call.ByID(3588044767);
}

export function StopAllGames(): $CancellablePromise<void> {
    return $Call.ByID(3163221018);
}

export function StopGame(id: string): $CancellablePromise<void> {
    return $Call.ByID(2413793942, id);
}
