// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService gestiona configuracion general, cache y hardware.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Config$0 from "../../Config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelIntegrityCheck(): $CancellablePromise<void> {
    return $Call.ByID(2684886775);
}

export function ClearAllCache(): $CancellablePromise<number> {
    return $Call.ByID(3931026362);
}

export function DeleteCacheCategory(category: string): $CancellablePromise<number> {
    return $Call.ByID(1533119815, category);
}

export function DeleteCacheEntry(category: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(2678592125, category, key);
}

export function DetectJavaInstallations(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1584013616);
}

export function GetCacheInfo(): $CancellablePromise<engine$0.CacheInfo> {
    return $Call.ByID(2399994306);
}

export function GetCheckForUpdatesOnStart(): $CancellablePromise<boolean> {
    return $Call.ByID(1043383842);
}

export function GetConfig(): $CancellablePromise<Config$0.Config> {
    return $Call.ByID(111049422);
}

export function GetIntegritySector(): $CancellablePromise<string> {
    return $Call.ByID(2255093393);
}

export function GetMinecraftConfig(): $CancellablePromise<Config$0.MinecraftConfig> {
    return $Call.ByID(2258576029);
}

export function GetSeparateGameDir(): $CancellablePromise<boolean> {
    return $Call.ByID(2775896702);
}

export function IntegrityStatus(): $CancellablePromise<engine$0.IntegrityProgress> {
    return $Call.ByID(3466624805);
}

export function MaxRAMGB(): $CancellablePromise<number> {
    return $Call.ByID(2567786719);
}

export function RecommendedRAM(): $CancellablePromise<$models.RecommendedRAMResult> {
    return $Call.ByID(3569969645);
}

export function RecommendedRAMGB(): $CancellablePromise<number> {
    return $Call.ByID(2420882516);
}

export function RefreshCache(category: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(476684451, category, key);
}

export function ResetConfig(): $CancellablePromise<void> {
    return $Call.ByID(1371130561);
}

export function SetAuthVerify(verify: boolean): $CancellablePromise<void> {
    return $Call.ByID(2998057555, verify);
}

export function SetCheckForUpdatesOnStart(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(3395588454, v);
}

export function SetConcurrentDownloads(n: number): $CancellablePromise<void> {
    return $Call.ByID(275444342, n);
}

export function SetIntegritySector(sector: string): $CancellablePromise<void> {
    return $Call.ByID(592277861, sector);
}

export function SetLaunchAfterInstall(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(634468086, v);
}

export function SetMaxMbps(mbps: number): $CancellablePromise<void> {
    return $Call.ByID(2336248852, mbps);
}

export function SetMaxRAM(gb: number): $CancellablePromise<void> {
    return $Call.ByID(3621401778, gb);
}

export function SetProxy(enabled: boolean, host: string, port: number, user: string, pass: string): $CancellablePromise<void> {
    return $Call.ByID(3506015068, enabled, host, port, user, pass);
}

export function SetSeparateGameDir(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(3421345930, v);
}

export function SetVerifyBeforeLaunch(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(977835725, v);
}

export function SetVerifyIntegrity(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(3701549576, v);
}

export function StartIntegrityCheck(scope: string): $CancellablePromise<void> {
    return $Call.ByID(1111849433, scope);
}

export function TotalRAMGB(): $CancellablePromise<number> {
    return $Call.ByID(4201320251);
}

export function UpdateMinecraftConfig(mc: Config$0.MinecraftConfig): $CancellablePromise<void> {
    return $Call.ByID(954916342, mc);
}
