// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RecommendedRAMResult {
    "minRam": number;
    "maxRam": number;
    "gcPreset": string;
}
