// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ExecutionPlan {
    "mainClass": string;
    "additionalClasspath": string[] | null;
    "additionalJvmArgs": string[] | null;
    "additionalGameArgs": string[] | null;
    "useModulePath": boolean;
}

export interface InstalledLoader {
    "loaderType": string;
    "loaderVersion": string;
    "minecraftVersion": string;
    "versionJsonId": string;
    "installerJarPath"?: string;
    "installedAt": number;
}

export interface LoaderVersion {
    "loaderVersion": string;
    "minecraftVersion": string;
    "stable": boolean;
}
