// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AccountCredentials {
    "username": string;
    "uuid": string;
    "accessToken": string;
    "userType"?: string;
}

export interface AccountInfo {
    "id": string;
    "name": string;
    "type": AccountType;
    "username": string;
    "uuid": string;
    "authServerUrl"?: string;
    "serverName"?: string;
    "hasToken": boolean;
    "sessionValid": boolean;
    "createdAt": string;
    "lastUsed"?: string;
    "customProperties"?: { [_ in string]?: string } | null;
}

export enum AccountType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeOffline = "offline",
    TypeAuthLib = "authlib",
};

export interface AuthlibLoginReq {
    "authServerUrl": string;
    "username": string;
    "password": string;
}

export interface CreateAccountReq {
    "type": AccountType;
    "name"?: string;
    "username": string;
    "accessToken"?: string;
    "authServerUrl"?: string;
    "uuid"?: string;
}
