// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService gestiona descargas y manifests.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as downloader$0 from "../../Core/Downloader/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export function CancelDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(3574424814, id);
}

export function FetchVersionManifest(): $CancellablePromise<downloader$0.Manifest | null> {
    return $Call.ByID(1482014581);
}

export function GetDownload(id: string): $CancellablePromise<engine$0.DownloadInfo | null> {
    return $Call.ByID(2986655152, id);
}

export function GetDownloadStatus(id: string): $CancellablePromise<engine$0.DownloadProgress | null> {
    return $Call.ByID(4012620562, id);
}

export function GetVersions(versionType: string): $CancellablePromise<engine$0.VersionInfo[] | null> {
    return $Call.ByID(3159988109, versionType);
}

export function ListDownloadedVersions(): $CancellablePromise<engine$0.InstalledVersion[] | null> {
    return $Call.ByID(3730864268);
}

export function ListDownloads(): $CancellablePromise<(engine$0.DownloadInfo | null)[] | null> {
    return $Call.ByID(4168266213);
}

export function PauseDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(197459158, id);
}

export function RefreshManifests(): $CancellablePromise<number> {
    return $Call.ByID(2047356203);
}

export function ResumeDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2708309123, id);
}

export function StartDownload(version: string, filter: engine$0.DownloadFilter, maxRetries: number, maxConcurrency: number, skipVerify: boolean, stallTimeoutMs: number, maxStallRetries: number): $CancellablePromise<engine$0.DownloadInfo | null> {
    return $Call.ByID(1070457592, version, filter, maxRetries, maxConcurrency, skipVerify, stallTimeoutMs, maxStallRetries);
}

export function StartFullDownload(version: string): $CancellablePromise<engine$0.DownloadInfo | null> {
    return $Call.ByID(4122406913, version);
}
