// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Assets {
    "fonts": FontSlot[] | null;
    "audio": MusicSlot[] | null;
    "gallery"?: GalleryBackground[] | null;
}

export interface FontSlot {
    "type": string;
    "name": string;
    "path": string;
}

export interface GalleryBackground {
    "path": string;
    "author": string;
    "modName": string;
    "url": string;
    "title"?: string;
}

export interface MusicSlot {
    "name": string;
    "path": string;
}
