// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModLoaderService gestiona instalacion y resolucion de mod loaders.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export function BuildModLoaderExecution(instancePath: string, versionsDir: string, librariesPath: string): $CancellablePromise<engine$0.ExecutionPlan | null> {
    return $Call.ByID(3431149251, instancePath, versionsDir, librariesPath);
}

export function GetInstalledInstanceModLoader(name: string): $CancellablePromise<engine$0.InstalledLoader | null> {
    return $Call.ByID(3392808088, name);
}

export function GetInstalledModLoader(instancePath: string): $CancellablePromise<engine$0.InstalledLoader | null> {
    return $Call.ByID(1053132945, instancePath);
}

export function GetModLoaderVersions(loader: string, mcVersion: string): $CancellablePromise<engine$0.ModLoaderVersion[] | null> {
    return $Call.ByID(3302307046, loader, mcVersion);
}

export function InstallInstanceModLoader(name: string, loader: string, loaderVersion: string, mcVersion: string): $CancellablePromise<engine$0.ModLoaderInstallResult | null> {
    return $Call.ByID(1491215675, name, loader, loaderVersion, mcVersion);
}

export function InstallModLoader(loader: string, loaderVersion: string, mcVersion: string, instancePath: string): $CancellablePromise<engine$0.ModLoaderInstallResult | null> {
    return $Call.ByID(301841754, loader, loaderVersion, mcVersion, instancePath);
}

export function ListModLoaders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1418619816);
}

export function RemoveInstanceModLoaderState(name: string): $CancellablePromise<void> {
    return $Call.ByID(454510175, name);
}

export function RemoveModLoaderState(instancePath: string): $CancellablePromise<void> {
    return $Call.ByID(2819442004, instancePath);
}

export function ResolveModLoaderVersion(loader: string, mcVersion: string, strategy: string): $CancellablePromise<string> {
    return $Call.ByID(3741892673, loader, mcVersion, strategy);
}
