// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Handlers$0 from "../../Handlers/models.js";

export type ScreenshotInfo = Handlers$0.ScreenshotInfo;
