// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstanceService gestiona CRUD de instancias y verificacion.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddInstanceVersion(name: string, req: engine$0.AddVersionReq): $CancellablePromise<$models.AddInstanceVersionResult | null> {
    return $Call.ByID(2807415334, name, req);
}

export function CancelInstanceDownload(dlID: string): $CancellablePromise<void> {
    return $Call.ByID(3621587611, dlID);
}

export function CancelInstanceVerify(name: string): $CancellablePromise<void> {
    return $Call.ByID(2067468242, name);
}

export function CloneInstance(name: string, newName: string, copyVersions: boolean): $CancellablePromise<engine$0.InstanceMetadata | null> {
    return $Call.ByID(150946184, name, newName, copyVersions);
}

export function CreateInstance(req: engine$0.CreateInstanceReq): $CancellablePromise<$models.CreateInstanceResult | null> {
    return $Call.ByID(2064582053, req);
}

export function CreateInstanceBackup(name: string): $CancellablePromise<string> {
    return $Call.ByID(724398495, name);
}

export function DeleteInstance(name: string): $CancellablePromise<void> {
    return $Call.ByID(3053395030, name);
}

export function GetInstance(name: string): $CancellablePromise<$models.GetInstanceResult | null> {
    return $Call.ByID(559008885, name);
}

export function GetInstanceDownloadStatus(dlID: string): $CancellablePromise<$models.InstanceDownloadStatusResult> {
    return $Call.ByID(3951186091, dlID);
}

export function ImportInstanceAsset(name: string, kind: string, src: string): $CancellablePromise<string> {
    return $Call.ByID(3579494144, name, kind, src);
}

export function InstanceVerifyStatus(name: string): $CancellablePromise<engine$0.InstanceVerifyProgress> {
    return $Call.ByID(3935227922, name);
}

export function ListInstanceScreenshots(instanceName: string): $CancellablePromise<$models.ScreenshotInfo[] | null> {
    return $Call.ByID(2188648982, instanceName);
}

export function ListInstanceVersions(name: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(263290780, name);
}

export function ListInstances(): $CancellablePromise<(engine$0.InstanceInfo | null)[] | null> {
    return $Call.ByID(1000038674);
}

export function OpenInstanceFolder(name: string): $CancellablePromise<void> {
    return $Call.ByID(3425812745, name);
}

export function PickInstanceAssetFile(): $CancellablePromise<string> {
    return $Call.ByID(1026247426);
}

export function RemoveInstanceVersion(name: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(2296318423, name, version);
}

export function StartInstanceVerify(name: string): $CancellablePromise<void> {
    return $Call.ByID(4268729472, name);
}

export function UpdateInstanceConfig(name: string, cfg: engine$0.InstanceLaunchConfig | null): $CancellablePromise<engine$0.InstanceLaunchConfig | null> {
    return $Call.ByID(2571770962, name, cfg);
}

export function UpdateInstanceMetadata(name: string, req: engine$0.UpdateMetadataReq): $CancellablePromise<engine$0.InstanceMetadata | null> {
    return $Call.ByID(2138958849, name, req);
}

export function VerifyInstance(name: string): $CancellablePromise<engine$0.VerifyResult[] | null> {
    return $Call.ByID(1869695676, name);
}

export function VerifyInstanceVersion(name: string, version: string): $CancellablePromise<engine$0.VerifyResult | null> {
    return $Call.ByID(544878736, name, version);
}
