// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstalledFile describe un archivo de contenido instalado en un destino.
 * Title es el nombre bonito declarado dentro del mod (vacío = usar Name).
 */
export interface InstalledFile {
    "kind": string;
    "name": string;
    "title": string;
    "size": number;
    "enabled": boolean;
}
