// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry representa una pista reproducida - CoverID apunta a cache/music/covers/*.zip
 */
export interface Entry {
    "path": string;
    "title": string;
    "artist": string;

    /**
     * legado: data URI, migrado a CoverID
     */
    "coverUrl"?: string;

    /**
     * hash de la carátula en cache comprimido
     */
    "coverId"?: string;
    "playedAt": string;
    "playCount": number;
}
