// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as Handlers$0 from "../../Handlers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export interface AddInstanceVersionResult {
    "downloadId": string;
    "version": string;
}

export interface CreateInstanceResult {
    "metadata": engine$0.InstanceMetadata | null;
    "downloadId": string;
}

export interface GetInstanceResult {
    "metadata": engine$0.InstanceMetadata | null;
    "config": engine$0.InstanceLaunchConfig | null;
}

export interface InstanceDownloadStatusResult {
    "id": string;
    "version": string;
    "state": string;
}

export type ScreenshotInfo = Handlers$0.ScreenshotInfo;
