// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Profile {
    "name": string;
    "version"?: string;
    "lastVersionId"?: string;
    "gameDir"?: string;
    "javaExec"?: string;
    "javaArgs"?: string;
    "resWidth"?: number;
    "resHeight"?: number;
    "fullscreen": boolean;
    "modLoader"?: string;
    "modLoaderVersion"?: string;
    "icon"?: string;
    "createdAt": string;
    "lastUsed"?: string;
    "customProperties"?: { [_ in string]?: string } | null;
}
