// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "cacheDir": string;
    "totalEntries": number;
    "totalBytes": number;
    "categories": { [_ in string]?: number } | null;
    "sizes": { [_ in string]?: number } | null;
    "ttls": { [_ in string]?: string } | null;
}
