// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";

export type DirectorySettings = engine$0.DirectoryInfo;

export interface LauncherVersionInfo {
    "currentVersion": string;
    "appName": string;
    "appAuthor": string;
    "updaterState": string;
    "updaterVersion": string;
}
