// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService gestiona lifecycle, directorios, updater y diagnostics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../../Handlers/Engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engineconfig$0 from "../../Handlers/Engine/engineconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(3928199103);
}

export function BootstrapComplete(durationMs: number, failedSteps: number): $CancellablePromise<void> {
    return $Call.ByID(4116397027, durationMs, failedSteps);
}

export function BootstrapLog(level: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3096519342, level, message);
}

export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2662039413);
}

export function EngineConfig(): $CancellablePromise<engineconfig$0.Config> {
    return $Call.ByID(3531655322);
}

export function EngineInfo(): $CancellablePromise<engine$0.EngineInfo> {
    return $Call.ByID(720987760);
}

export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(851251795);
}

export function GetDirectorySettings(): $CancellablePromise<$models.DirectorySettings> {
    return $Call.ByID(3434098788);
}

export function GetFirstLaunch(): $CancellablePromise<boolean> {
    return $Call.ByID(822050259);
}

export function GetLauncherVersionInfo(): $CancellablePromise<$models.LauncherVersionInfo> {
    return $Call.ByID(1860162442);
}

export function LocalAssetsDir(): $CancellablePromise<string> {
    return $Call.ByID(4127440287);
}

export function NewsLoadChangelog(version: string): $CancellablePromise<void> {
    return $Call.ByID(2904876945, version);
}

export function NewsLoadMarkdown(url: string): $CancellablePromise<void> {
    return $Call.ByID(3101763732, url);
}

export function NewsLoadRelease(version: string): $CancellablePromise<void> {
    return $Call.ByID(1928367782, version);
}

export function NewsRefreshIndex(): $CancellablePromise<void> {
    return $Call.ByID(4104902204);
}

/**
 * OpenHomepage abre la página principal del launcher en el navegador externo.
 */
export function OpenHomepage(): $CancellablePromise<void> {
    return $Call.ByID(3863758818);
}

export function OpenPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3697010533, path);
}

export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1449535686);
}

export function ReadAbsoluteFile(path: string): $CancellablePromise<string | null> {
    return $Call.ByID(2352574489, path);
}

export function ReadLocalFile(rel: string): $CancellablePromise<string | null> {
    return $Call.ByID(1613660043, rel);
}

/**
 * RefreshTray fuerza la reconstrucción del menú del tray (p. ej. tras crear/borrar playlist).
 */
export function RefreshTray(): $CancellablePromise<void> {
    return $Call.ByID(3580314685);
}

/**
 * ReloadWindow recarga la interfaz de la ventana principal (equivalente a F5).
 */
export function ReloadWindow(): $CancellablePromise<void> {
    return $Call.ByID(1150960667);
}

export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(147233424);
}

export function SetDirectoryMode(mode: string, customPath: string): $CancellablePromise<void> {
    return $Call.ByID(4002158122, mode, customPath);
}

export function SetFirstLaunchDone(): $CancellablePromise<void> {
    return $Call.ByID(1106831627);
}

export function UpdateEngineConfig(cfg: engineconfig$0.Config): $CancellablePromise<void> {
    return $Call.ByID(1025301179, cfg);
}

/**
 * UpdateTrayLibraryState sincroniza el estado de la biblioteca musical con el tray
 * para que los controles reproducir/pausar/siguiente/anterior reflejen correctamente
 * habilitados/deshabilitados y etiqueta. Es invocado desde el frontend (PlayerStore).
 */
export function UpdateTrayLibraryState(playing: boolean, hasNext: boolean, hasPrev: boolean, hasQueue: boolean): $CancellablePromise<void> {
    return $Call.ByID(263804387, playing, hasNext, hasPrev, hasQueue);
}

export function WailsCheckForUpdate(): $CancellablePromise<void> {
    return $Call.ByID(235383534);
}

export function WailsGetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(2068715995);
}

export function WailsGetState(): $CancellablePromise<string> {
    return $Call.ByID(3089725577);
}

export function WailsInstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1910558842);
}

export function WailsRestart(): $CancellablePromise<void> {
    return $Call.ByID(1653087715);
}

export function WailsSkipVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(715844065, version);
}
