// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DownloadFilter {
    "version": string;
    "client": boolean;
    "libraries": boolean;
    "natives": boolean;
    "assets": boolean;
    "java": boolean;
}

export interface DownloadProgress {
    "mbDownloaded": number;
    "mbTotal": number;
    "percent": number;
    "state": DownloadState;
    "currentSection": string;
    "sectionsCompleted": string[] | null;
    "sectionsTotal": number;
    "filesDownloaded": number;
    "filesTotal": number;
    "filesExisting": number;
    "currentFile": string;
    "currentUrl": string;
    "currentDest": string;
    "currentProgress": number;
    "log": string[] | null;
    "sections": SectionProgress[] | null;
    "activeFiles": FileProgress[] | null;
    "queuedCount": number;
    "queuedPreview": string[] | null;
    "speedMbps": number;
}

export enum DownloadState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatePending = "pending",
    StateDownloading = "downloading",
    StatePaused = "paused",
    StateCancelled = "cancelled",
    StateCompleted = "completed",
    StateError = "error",
    StateVerifying = "verifying",
    StateReDownload = "redownloading",
};

export interface FileProgress {
    "name": string;
    "section": string;
    "size": number;
    "downloaded": number;
    "percent": number;
    "state": string;
}

export interface LatestInfo {
    "release": string;
    "snapshot": string;
}

export interface Manifest {
    "versions": ManifestVersion[] | null;
    "latest": LatestInfo;
}

export interface ManifestVersion {
    "id": string;
    "url": string;
    "type": string;
    "releaseTime": string;
}

export interface SectionProgress {
    "name": string;
    "totalFiles": number;
    "doneFiles": number;
    "mbTotal": number;
    "mbDownloaded": number;
}
