// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instance} from '../models';
import {main} from '../models';
import {modloader} from '../models';
import {profile} from '../models';
import {config} from '../models';
import {engine} from '../models';
import {downloader} from '../models';
import {cache} from '../models';
import {Config} from '../models';
import {history} from '../models';
import {launcher} from '../models';

export function AddInstanceVersion(arg1:string,arg2:instance.AddVersionReq):Promise<main.AddInstanceVersionResult>;

export function BuildModLoaderExecution(arg1:string,arg2:string,arg3:string):Promise<modloader.ExecutionPlan>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelInstanceDownload(arg1:string):Promise<void>;

export function ClearAllCache():Promise<number>;

export function ClearHistory():Promise<number>;

export function CloneInstance(arg1:string,arg2:string,arg3:boolean):Promise<instance.InstanceMetadata>;

export function CreateInstance(arg1:instance.CreateInstanceReq):Promise<main.CreateInstanceResult>;

export function CreateProfile(arg1:profile.Profile):Promise<void>;

export function DeleteCacheCategory(arg1:string):Promise<number>;

export function DeleteCacheEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteHistoryEntry(arg1:string):Promise<boolean>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DetectJavaInstallations():Promise<Array<string>>;

export function EngineConfig():Promise<config.Config>;

export function EngineInfo():Promise<engine.EngineInfo>;

export function FetchVersionManifest():Promise<downloader.Manifest>;

export function GetCacheInfo():Promise<cache.Info>;

export function GetConfig():Promise<Config.Config>;

export function GetDownload(arg1:string):Promise<engine.DownloadInfo>;

export function GetDownloadStatus(arg1:string):Promise<downloader.DownloadProgress>;

export function GetGame(arg1:string):Promise<engine.GameResp>;

export function GetHistory():Promise<Array<history.Entry>>;

export function GetHistoryByVersion(arg1:string):Promise<Array<history.Entry>>;

export function GetHistoryStats():Promise<main.HistoryStatsResult>;

export function GetInstalledModLoader(arg1:string):Promise<modloader.InstalledLoader>;

export function GetInstance(arg1:string):Promise<main.GetInstanceResult>;

export function GetInstanceDownloadStatus(arg1:string):Promise<main.InstanceDownloadStatusResult>;

export function GetMinecraftConfig():Promise<Config.MinecraftConfig>;

export function GetModLoaderVersions(arg1:string,arg2:string):Promise<Array<modloader.LoaderVersion>>;

export function GetMostPlayed(arg1:number):Promise<Array<history.Entry>>;

export function GetProfile(arg1:string):Promise<profile.Profile>;

export function GetRecentHistory(arg1:number):Promise<Array<history.Entry>>;

export function GetSelectedProfile():Promise<string>;

export function GetUIScale():Promise<number>;

export function GetVersions(arg1:string):Promise<Array<engine.VersionInfo>>;

export function ImportBackground(arg1:string,arg2:string):Promise<string>;

export function InstallModLoader(arg1:string,arg2:string,arg3:string,arg4:string):Promise<engine.ModLoaderInstallResult>;

export function LaunchInstance(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<instance.InstanceLaunchResult>;

export function LaunchMinecraft(arg1:launcher.LaunchConfig):Promise<engine.GameResp>;

export function ListDownloads():Promise<Array<engine.DownloadInfo>>;

export function ListGames():Promise<Array<engine.GameResp>>;

export function ListInstanceVersions(arg1:string):Promise<Array<string>>;

export function ListInstances():Promise<Array<instance.InstanceInfo>>;

export function ListModLoaders():Promise<Array<string>>;

export function ListProfiles():Promise<Record<string, profile.Profile>>;

export function LocalAssetsDir():Promise<string>;

export function MaxRAMGB():Promise<number>;

export function PauseDownload(arg1:string):Promise<void>;

export function PickBackgroundFile(arg1:string):Promise<string>;

export function ReadLocalFile(arg1:string):Promise<Array<number>>;

export function RecommendedRAM():Promise<main.RecommendedRAMResult>;

export function RecommendedRAMGB():Promise<number>;

export function RefreshCache(arg1:string,arg2:string):Promise<void>;

export function RemoveInstanceVersion(arg1:string,arg2:string):Promise<void>;

export function RemoveModLoaderState(arg1:string):Promise<void>;

export function ResetConfig():Promise<void>;

export function ResolveModLoaderVersion(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SetAuthVerify(arg1:boolean):Promise<void>;

export function SetConcurrentDownloads(arg1:number):Promise<void>;

export function SetMaxMbps(arg1:number):Promise<void>;

export function SetMaxRAM(arg1:number):Promise<void>;

export function SetProxy(arg1:boolean,arg2:string,arg3:number,arg4:string,arg5:string):Promise<void>;

export function SetSelectedProfile(arg1:string):Promise<void>;

export function SetUIScale(arg1:number):Promise<void>;

export function StartDownload(arg1:string,arg2:downloader.DownloadFilter,arg3:number,arg4:number,arg5:boolean,arg6:number,arg7:number):Promise<engine.DownloadInfo>;

export function StartFullDownload(arg1:string):Promise<engine.DownloadInfo>;

export function StopAllGames():Promise<void>;

export function StopGame(arg1:string):Promise<void>;

export function TotalRAMGB():Promise<number>;

export function UpdateEngineConfig(arg1:config.Config):Promise<void>;

export function UpdateInstanceConfig(arg1:string,arg2:instance.InstanceLaunchConfig):Promise<instance.InstanceLaunchConfig>;

export function UpdateInstanceMetadata(arg1:string,arg2:instance.UpdateMetadataReq):Promise<instance.InstanceMetadata>;

export function UpdateMinecraftConfig(arg1:Config.MinecraftConfig):Promise<void>;

export function UpdatePersonalization(arg1:Config.Personalization):Promise<void>;

export function UpdateProfile(arg1:string,arg2:profile.Profile):Promise<void>;

export function VerifyInstance(arg1:string):Promise<Array<instance.VerifyResult>>;

export function VerifyInstanceVersion(arg1:string,arg2:string):Promise<instance.VerifyResult>;
