// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['AddInstanceVersion'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function BuildModLoaderExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildModLoaderExecution'](arg1, arg2, arg3);
}

export function CancelAuthlibLogin() {
  return window['go']['main']['App']['CancelAuthlibLogin']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelInstanceDownload(arg1) {
  return window['go']['main']['App']['CancelInstanceDownload'](arg1);
}

export function CancelIntegrityCheck() {
  return window['go']['main']['App']['CancelIntegrityCheck']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloneInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneInstance'](arg1, arg2, arg3);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateInstance(arg1) {
  return window['go']['main']['App']['CreateInstance'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteCacheCategory(arg1) {
  return window['go']['main']['App']['DeleteCacheCategory'](arg1);
}

export function DeleteCacheEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteCacheEntry'](arg1, arg2);
}

export function DeleteFontFile(arg1) {
  return window['go']['main']['App']['DeleteFontFile'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectJavaInstallations() {
  return window['go']['main']['App']['DetectJavaInstallations']();
}

export function EngineConfig() {
  return window['go']['main']['App']['EngineConfig']();
}

export function EngineInfo() {
  return window['go']['main']['App']['EngineInfo']();
}

export function FetchVersionManifest() {
  return window['go']['main']['App']['FetchVersionManifest']();
}

export function GetAccount(arg1) {
  return window['go']['main']['App']['GetAccount'](arg1);
}

export function GetAccountAssets(arg1) {
  return window['go']['main']['App']['GetAccountAssets'](arg1);
}

export function GetAccountsAutoRefresh() {
  return window['go']['main']['App']['GetAccountsAutoRefresh']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetCheckForUpdatesOnStart() {
  return window['go']['main']['App']['GetCheckForUpdatesOnStart']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCrashHistory() {
  return window['go']['main']['App']['GetCrashHistory']();
}

export function GetDirectorySettings() {
  return window['go']['main']['App']['GetDirectorySettings']();
}

export function GetDownload(arg1) {
  return window['go']['main']['App']['GetDownload'](arg1);
}

export function GetDownloadStatus(arg1) {
  return window['go']['main']['App']['GetDownloadStatus'](arg1);
}

export function GetFirstLaunch() {
  return window['go']['main']['App']['GetFirstLaunch']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetGameLaunchInfo(arg1) {
  return window['go']['main']['App']['GetGameLaunchInfo'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryByVersion(arg1) {
  return window['go']['main']['App']['GetHistoryByVersion'](arg1);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetInstalledInstanceModLoader(arg1) {
  return window['go']['main']['App']['GetInstalledInstanceModLoader'](arg1);
}

export function GetInstalledModLoader(arg1) {
  return window['go']['main']['App']['GetInstalledModLoader'](arg1);
}

export function GetInstance(arg1) {
  return window['go']['main']['App']['GetInstance'](arg1);
}

export function GetInstanceDownloadStatus(arg1) {
  return window['go']['main']['App']['GetInstanceDownloadStatus'](arg1);
}

export function GetInstanceStats(arg1) {
  return window['go']['main']['App']['GetInstanceStats'](arg1);
}

export function GetIntegritySector() {
  return window['go']['main']['App']['GetIntegritySector']();
}

export function GetLauncherAssets() {
  return window['go']['main']['App']['GetLauncherAssets']();
}

export function GetMinecraftConfig() {
  return window['go']['main']['App']['GetMinecraftConfig']();
}

export function GetModLoaderVersions(arg1, arg2) {
  return window['go']['main']['App']['GetModLoaderVersions'](arg1, arg2);
}

export function GetMostPlayed(arg1) {
  return window['go']['main']['App']['GetMostPlayed'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetRecentHistory(arg1) {
  return window['go']['main']['App']['GetRecentHistory'](arg1);
}

export function GetRichPresenceConfig() {
  return window['go']['main']['App']['GetRichPresenceConfig']();
}

export function GetSelectedAccount() {
  return window['go']['main']['App']['GetSelectedAccount']();
}

export function GetSelectedProfile() {
  return window['go']['main']['App']['GetSelectedProfile']();
}

export function GetSelectedVersion() {
  return window['go']['main']['App']['GetSelectedVersion']();
}

export function GetSeparateGameDir() {
  return window['go']['main']['App']['GetSeparateGameDir']();
}

export function GetUIScale() {
  return window['go']['main']['App']['GetUIScale']();
}

export function GetVersions(arg1) {
  return window['go']['main']['App']['GetVersions'](arg1);
}

export function ImportBackground(arg1, arg2) {
  return window['go']['main']['App']['ImportBackground'](arg1, arg2);
}

export function ImportFont(arg1) {
  return window['go']['main']['App']['ImportFont'](arg1);
}

export function ImportInstanceAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportInstanceAsset'](arg1, arg2, arg3);
}

export function InstallInstanceModLoader(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallInstanceModLoader'](arg1, arg2, arg3, arg4);
}

export function InstallModLoader(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallModLoader'](arg1, arg2, arg3, arg4);
}

export function IntegrityStatus() {
  return window['go']['main']['App']['IntegrityStatus']();
}

export function LaunchInstance(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LaunchInstance'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LaunchMinecraft(arg1) {
  return window['go']['main']['App']['LaunchMinecraft'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListDownloadedVersions() {
  return window['go']['main']['App']['ListDownloadedVersions']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function ListFontFiles() {
  return window['go']['main']['App']['ListFontFiles']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListInstanceScreenshots(arg1) {
  return window['go']['main']['App']['ListInstanceScreenshots'](arg1);
}

export function ListInstanceVersions(arg1) {
  return window['go']['main']['App']['ListInstanceVersions'](arg1);
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListModLoaders() {
  return window['go']['main']['App']['ListModLoaders']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListScreenshots() {
  return window['go']['main']['App']['ListScreenshots']();
}

export function LocalAssetsDir() {
  return window['go']['main']['App']['LocalAssetsDir']();
}

export function LoginAuthlib(arg1) {
  return window['go']['main']['App']['LoginAuthlib'](arg1);
}

export function MaxRAMGB() {
  return window['go']['main']['App']['MaxRAMGB']();
}

export function NewsLoadChangelog(arg1) {
  return window['go']['main']['App']['NewsLoadChangelog'](arg1);
}

export function NewsLoadMarkdown(arg1) {
  return window['go']['main']['App']['NewsLoadMarkdown'](arg1);
}

export function NewsLoadRelease(arg1) {
  return window['go']['main']['App']['NewsLoadRelease'](arg1);
}

export function NewsRefreshIndex() {
  return window['go']['main']['App']['NewsRefreshIndex']();
}

export function OpenInstanceFolder(arg1) {
  return window['go']['main']['App']['OpenInstanceFolder'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PickBackgroundFile(arg1) {
  return window['go']['main']['App']['PickBackgroundFile'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFontFile() {
  return window['go']['main']['App']['PickFontFile']();
}

export function PickInstanceAssetFile() {
  return window['go']['main']['App']['PickInstanceAssetFile']();
}

export function ReadLocalFile(arg1) {
  return window['go']['main']['App']['ReadLocalFile'](arg1);
}

export function RecommendedRAM() {
  return window['go']['main']['App']['RecommendedRAM']();
}

export function RecommendedRAMGB() {
  return window['go']['main']['App']['RecommendedRAMGB']();
}

export function RefreshAccount(arg1) {
  return window['go']['main']['App']['RefreshAccount'](arg1);
}

export function RefreshAllAccounts() {
  return window['go']['main']['App']['RefreshAllAccounts']();
}

export function RefreshCache(arg1, arg2) {
  return window['go']['main']['App']['RefreshCache'](arg1, arg2);
}

export function RefreshManifests() {
  return window['go']['main']['App']['RefreshManifests']();
}

export function RemoveInstanceModLoaderState(arg1) {
  return window['go']['main']['App']['RemoveInstanceModLoaderState'](arg1);
}

export function RemoveInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['RemoveInstanceVersion'](arg1, arg2);
}

export function RemoveModLoaderState(arg1) {
  return window['go']['main']['App']['RemoveModLoaderState'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ResolveAccountCredentials(arg1) {
  return window['go']['main']['App']['ResolveAccountCredentials'](arg1);
}

export function ResolveModLoaderVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveModLoaderVersion'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveLauncherAssets(arg1) {
  return window['go']['main']['App']['SaveLauncherAssets'](arg1);
}

export function SetAccountsAutoRefresh(arg1) {
  return window['go']['main']['App']['SetAccountsAutoRefresh'](arg1);
}

export function SetAuthVerify(arg1) {
  return window['go']['main']['App']['SetAuthVerify'](arg1);
}

export function SetCheckForUpdatesOnStart(arg1) {
  return window['go']['main']['App']['SetCheckForUpdatesOnStart'](arg1);
}

export function SetConcurrentDownloads(arg1) {
  return window['go']['main']['App']['SetConcurrentDownloads'](arg1);
}

export function SetDirectoryMode(arg1, arg2) {
  return window['go']['main']['App']['SetDirectoryMode'](arg1, arg2);
}

export function SetFirstLaunchDone() {
  return window['go']['main']['App']['SetFirstLaunchDone']();
}

export function SetHideLauncher(arg1) {
  return window['go']['main']['App']['SetHideLauncher'](arg1);
}

export function SetIdle(arg1) {
  return window['go']['main']['App']['SetIdle'](arg1);
}

export function SetIntegritySector(arg1) {
  return window['go']['main']['App']['SetIntegritySector'](arg1);
}

export function SetLaunchAfterInstall(arg1) {
  return window['go']['main']['App']['SetLaunchAfterInstall'](arg1);
}

export function SetMaxMbps(arg1) {
  return window['go']['main']['App']['SetMaxMbps'](arg1);
}

export function SetMaxRAM(arg1) {
  return window['go']['main']['App']['SetMaxRAM'](arg1);
}

export function SetProxy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetProxy'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRichPresenceEnabled(arg1) {
  return window['go']['main']['App']['SetRichPresenceEnabled'](arg1);
}

export function SetSelectedAccount(arg1) {
  return window['go']['main']['App']['SetSelectedAccount'](arg1);
}

export function SetSelectedProfile(arg1) {
  return window['go']['main']['App']['SetSelectedProfile'](arg1);
}

export function SetSelectedVersion(arg1) {
  return window['go']['main']['App']['SetSelectedVersion'](arg1);
}

export function SetSeparateGameDir(arg1) {
  return window['go']['main']['App']['SetSeparateGameDir'](arg1);
}

export function SetUIScale(arg1) {
  return window['go']['main']['App']['SetUIScale'](arg1);
}

export function SetVerifyIntegrity(arg1) {
  return window['go']['main']['App']['SetVerifyIntegrity'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartFullDownload(arg1) {
  return window['go']['main']['App']['StartFullDownload'](arg1);
}

export function StartIntegrityCheck(arg1) {
  return window['go']['main']['App']['StartIntegrityCheck'](arg1);
}

export function StopAllGames() {
  return window['go']['main']['App']['StopAllGames']();
}

export function StopGame(arg1) {
  return window['go']['main']['App']['StopGame'](arg1);
}

export function TotalRAMGB() {
  return window['go']['main']['App']['TotalRAMGB']();
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateEngineConfig(arg1) {
  return window['go']['main']['App']['UpdateEngineConfig'](arg1);
}

export function UpdateInstanceConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceConfig'](arg1, arg2);
}

export function UpdateInstanceMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceMetadata'](arg1, arg2);
}

export function UpdateMinecraftConfig(arg1) {
  return window['go']['main']['App']['UpdateMinecraftConfig'](arg1);
}

export function UpdatePersonalization(arg1) {
  return window['go']['main']['App']['UpdatePersonalization'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function VerifyInstance(arg1) {
  return window['go']['main']['App']['VerifyInstance'](arg1);
}

export function VerifyInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['VerifyInstanceVersion'](arg1, arg2);
}
