// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['AddInstanceVersion'](arg1, arg2);
}

export function BuildModLoaderExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildModLoaderExecution'](arg1, arg2, arg3);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelInstanceDownload(arg1) {
  return window['go']['main']['App']['CancelInstanceDownload'](arg1);
}

export function ClearAllCache() {
  return window['go']['main']['App']['ClearAllCache']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloneInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneInstance'](arg1, arg2, arg3);
}

export function CreateInstance(arg1) {
  return window['go']['main']['App']['CreateInstance'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteCacheCategory(arg1) {
  return window['go']['main']['App']['DeleteCacheCategory'](arg1);
}

export function DeleteCacheEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteCacheEntry'](arg1, arg2);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectJavaInstallations() {
  return window['go']['main']['App']['DetectJavaInstallations']();
}

export function EngineConfig() {
  return window['go']['main']['App']['EngineConfig']();
}

export function EngineInfo() {
  return window['go']['main']['App']['EngineInfo']();
}

export function FetchVersionManifest() {
  return window['go']['main']['App']['FetchVersionManifest']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownload(arg1) {
  return window['go']['main']['App']['GetDownload'](arg1);
}

export function GetDownloadStatus(arg1) {
  return window['go']['main']['App']['GetDownloadStatus'](arg1);
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryByVersion(arg1) {
  return window['go']['main']['App']['GetHistoryByVersion'](arg1);
}

export function GetHistoryStats() {
  return window['go']['main']['App']['GetHistoryStats']();
}

export function GetInstalledModLoader(arg1) {
  return window['go']['main']['App']['GetInstalledModLoader'](arg1);
}

export function GetInstance(arg1) {
  return window['go']['main']['App']['GetInstance'](arg1);
}

export function GetInstanceDownloadStatus(arg1) {
  return window['go']['main']['App']['GetInstanceDownloadStatus'](arg1);
}

export function GetMinecraftConfig() {
  return window['go']['main']['App']['GetMinecraftConfig']();
}

export function GetModLoaderVersions(arg1, arg2) {
  return window['go']['main']['App']['GetModLoaderVersions'](arg1, arg2);
}

export function GetMostPlayed(arg1) {
  return window['go']['main']['App']['GetMostPlayed'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetRecentHistory(arg1) {
  return window['go']['main']['App']['GetRecentHistory'](arg1);
}

export function GetSelectedProfile() {
  return window['go']['main']['App']['GetSelectedProfile']();
}

export function GetUIScale() {
  return window['go']['main']['App']['GetUIScale']();
}

export function GetVersions(arg1) {
  return window['go']['main']['App']['GetVersions'](arg1);
}

export function ImportBackground(arg1, arg2) {
  return window['go']['main']['App']['ImportBackground'](arg1, arg2);
}

export function InstallModLoader(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallModLoader'](arg1, arg2, arg3, arg4);
}

export function LaunchInstance(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LaunchInstance'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LaunchMinecraft(arg1) {
  return window['go']['main']['App']['LaunchMinecraft'](arg1);
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListInstanceVersions(arg1) {
  return window['go']['main']['App']['ListInstanceVersions'](arg1);
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListModLoaders() {
  return window['go']['main']['App']['ListModLoaders']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LocalAssetsDir() {
  return window['go']['main']['App']['LocalAssetsDir']();
}

export function MaxRAMGB() {
  return window['go']['main']['App']['MaxRAMGB']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function PickBackgroundFile(arg1) {
  return window['go']['main']['App']['PickBackgroundFile'](arg1);
}

export function ReadLocalFile(arg1) {
  return window['go']['main']['App']['ReadLocalFile'](arg1);
}

export function RecommendedRAM() {
  return window['go']['main']['App']['RecommendedRAM']();
}

export function RecommendedRAMGB() {
  return window['go']['main']['App']['RecommendedRAMGB']();
}

export function RefreshCache(arg1, arg2) {
  return window['go']['main']['App']['RefreshCache'](arg1, arg2);
}

export function RemoveInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['RemoveInstanceVersion'](arg1, arg2);
}

export function RemoveModLoaderState(arg1) {
  return window['go']['main']['App']['RemoveModLoaderState'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ResolveModLoaderVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveModLoaderVersion'](arg1, arg2, arg3);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SetAuthVerify(arg1) {
  return window['go']['main']['App']['SetAuthVerify'](arg1);
}

export function SetConcurrentDownloads(arg1) {
  return window['go']['main']['App']['SetConcurrentDownloads'](arg1);
}

export function SetMaxMbps(arg1) {
  return window['go']['main']['App']['SetMaxMbps'](arg1);
}

export function SetMaxRAM(arg1) {
  return window['go']['main']['App']['SetMaxRAM'](arg1);
}

export function SetProxy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetProxy'](arg1, arg2, arg3, arg4, arg5);
}

export function SetSelectedProfile(arg1) {
  return window['go']['main']['App']['SetSelectedProfile'](arg1);
}

export function SetUIScale(arg1) {
  return window['go']['main']['App']['SetUIScale'](arg1);
}

export function StartDownload(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartFullDownload(arg1) {
  return window['go']['main']['App']['StartFullDownload'](arg1);
}

export function StopAllGames() {
  return window['go']['main']['App']['StopAllGames']();
}

export function StopGame(arg1) {
  return window['go']['main']['App']['StopGame'](arg1);
}

export function TotalRAMGB() {
  return window['go']['main']['App']['TotalRAMGB']();
}

export function UpdateEngineConfig(arg1) {
  return window['go']['main']['App']['UpdateEngineConfig'](arg1);
}

export function UpdateInstanceConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceConfig'](arg1, arg2);
}

export function UpdateInstanceMetadata(arg1, arg2) {
  return window['go']['main']['App']['UpdateInstanceMetadata'](arg1, arg2);
}

export function UpdateMinecraftConfig(arg1) {
  return window['go']['main']['App']['UpdateMinecraftConfig'](arg1);
}

export function UpdatePersonalization(arg1) {
  return window['go']['main']['App']['UpdatePersonalization'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}

export function VerifyInstance(arg1) {
  return window['go']['main']['App']['VerifyInstance'](arg1);
}

export function VerifyInstanceVersion(arg1, arg2) {
  return window['go']['main']['App']['VerifyInstanceVersion'](arg1, arg2);
}
